### ISSUE TITLE
Build TL version of SLA License Issuance dashboard? Or just have one SLA License Issuance dashboard for all licenses?

### ISSUE THREAD

**Issue by pribbens** [CityOfPhiladelphia/LI_dashboards#53]

**Comment by ShannonKHolm** [comment]
As long as it doesn't affect performance too much, I think keep them together

**Comment by pribbens** [comment]
Ended up creating a separate SLA TL dashboard. Combining them would have made things a little slower, the data a little harder to interpret, and would have taken more work to create.
