### ISSUE TITLE
Build Incomplete Processes dashboard

### ISSUE THREAD

**Issue by pribbens** [CityOfPhiladelphia/LI_dashboards#95]
Like Individual Workloads, but for incomplete processes instead of completed ones.

**Comment by pribbens** [comment]
@ShannonKHolm I can't remember who the origin of this request was, but wouldn't this be very similar to the Active Processes dashboards that already exist? Do we need to create this as a separate one? Seems like the only differences would be that it would include all types of jobs and processes and statuses (whereas Active Processes only include some of those), and that it would provide info on who the process is assigned to.

**Comment by pribbens** [comment]
@ShannonKHolm Is there any way we can pare down this dataset? The query I wrote (G:\01_Philip_Ribbens_Project_Folder\dashboards\LI_dashboards_clean\LI_dashboards\etl\queries\incomplete_processes.sql) returns over 150,000 rows and when I tried to load the dashboard with all that data it crashed the webpage. So we'll need to find a way to reduce the amount of data we're working with on this dashboard.

**Comment by pribbens** [comment]
@ShannonKHolm Can I split out business licenses and trade licenses into separate dashboards? That would be a start

**Comment by ShannonKHolm** [comment]
Yea split them first and see how that helps.

**Comment by pribbens** [comment]
Turns out it wasn't b/c of all the rows, but b/c some of the values of the ASSIGNEDSTAFF field were huge. Quite a few if the processes were assigned to 70+ staff members, and apparently the really long strings listing all of them resulted in too much data for the browser to handle. So I changed the queries so that if there was more than 1 staff assigned then it just says "multiple" for Assigned Staff and then I added a "Num of Assigned Staff" field that reports the number of staff assigned
