### ISSUE TITLE
Add links to application in POSSE to LicensesWithCompletenessChecksButNoCompletedInspections

### ISSUE THREAD

**Issue by pribbens** [CityOfPhiladelphia/LI_dashboards#96]

**Comment by pribbens** [comment]
Does Delia mean the links to the job or the license?

**Comment by ShannonKHolm** [comment]
On the Job, since this is where the Completeness Check is.

**Comment by pribbens** [comment]
Are all inspections linked to a job or are some only linked directly to a license?

**Comment by ShannonKHolm** [comment]
Completeness Checks are only linked to a job, inspections can be on either
